services:
  app:
    build: .
    restart: on-failure
    ports:
      - ${PORT}:${PORT}
    networks:
      - backend
    environment:
      PORT: ${PORT}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1GB
    command: sh -c "npm start"
networks:
  backend:
    driver: bridge
